import type { Metadata } from "next";
import { Header } from "@/components/Header";
import localFont from "next/font/local";
import "../styles/globals.scss";
import { Footer } from "@/components/Footer";

const clasDisplay = localFont({
	variable: "--font-clash-display",
	src: [
		{
			path: "../fonts/ClashDisplay-Regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "../fonts/ClashDisplay-Medium.woff2",
			weight: "500",
			style: "normal",
		},
		{
			path: "../fonts/ClashDisplay-Semibold.woff2",
			weight: "600",
			style: "normal",
		},
		{
			path: "../fonts/ClashDisplay-Bold.woff2",
			weight: "700",
			style: "normal",
		},
	],
});

export const metadata: Metadata = {
	title: "uifry™",
	description: "Generated by create next app",
	icons: {
		icon: "/img/icons/favicon.png",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${clasDisplay.variable}`}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
